title:             Developer Lim
email:             dahun0101@gmail.com
description:       개발자
author:            Dahun Lim
baseurl:           "/"
url:               "http://dahunlim.github.io"

# Social Profiles
# twitter_username:  SBootstrap
github_username:   dahunlim
facebook_username: dahun.lim

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
